apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harshavardana-reddy/Kubernetes_Istio_ArgoCD_Monitoring.git  # Update with your repo URL
    targetRevision: main
    path: ./
    directory:
      recurse: true
      include: "*.yaml"
      exclude: "{argocd/**,k8s-ingress.yaml,**/kustomization.yaml,**/kustomization.yml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
